/* Auto-generated by group11_balance.deploy.export_to_c.py -- DO NOT EDIT */
#ifndef GROUP11_POLICY_H
#define GROUP11_POLICY_H

#include <math.h>

#define GROUP11_ALGO_PPO 1
#define GROUP11_NUM_LAYERS 1
#define GROUP11_OBS_DIM 8
#define GROUP11_ACTION_DIM 1
#define GROUP11_MAX_WIDTH 8
#define GROUP11_PARAM_COUNT 9
#define GROUP11_U_MAX 8.00000000e+03f
#define GROUP11_TASK_BALANCE 1
#define GROUP11_TARGET_WHEEL_VELOCITY 0.00000000e+00f

/*
state order:
  theta_l, theta_r, theta_l_dot, theta_r_dot,
  body_angle, body_rate, pole_angle, pole_rate
action output:
  action[0], action[1] are physical left/right wheel control values.
  The learned actor emits one normalized common-mode action in [-1, 1],
  then this header maps it to [u, u] by multiplying GROUP11_U_MAX.
task: balance
target_wheel_velocity_rad_s: 0.000000
*/

static const float GROUP11_W0[1][8] = {
  {-4.44782339e-03f, -4.44782339e-03f, -6.77107228e-03f, -6.77107228e-03f, 6.86325490e-01f, -5.58737405e-02f, -2.36402965e+00f, -3.70160192e-01f},
};
static const float GROUP11_B0[1] = {0.00000000e+00f};
#define GROUP11_LAYER0_IN 8
#define GROUP11_LAYER0_OUT 1
#define GROUP11_LAYER0_ACT_IDENTITY 1

static float group11_clip(float x, float lo, float hi) {
  if (x < lo) return lo;
  if (x > hi) return hi;
  return x;
}

static float group11_activation(float x, int act_id) {
  if (act_id == 1) return x > 0.0f ? x : 0.0f;
  if (act_id == 2) return tanhf(x);
  return x;
}

static void group11_dense(const float *in, float *out, const float *w, const float *b, int in_dim, int out_dim, int act_id) {
  int i, j;
  for (i = 0; i < out_dim; i++) {
    float y = b[i];
    for (j = 0; j < in_dim; j++) y += w[i * in_dim + j] * in[j];
    out[i] = group11_activation(y, act_id);
  }
}

static void group11_policy_raw(const float state[8], float raw[1]) {
  float buf0[GROUP11_MAX_WIDTH];
  float buf1[GROUP11_MAX_WIDTH];
  const float *in = state;

  group11_dense(in, raw, (const float *)GROUP11_W0, GROUP11_B0, GROUP11_LAYER0_IN, GROUP11_LAYER0_OUT, 0);

}

static void group11_policy_predict(const float state[8], float action[2]) {
  float raw[1];
  float u;
  group11_policy_raw(state, raw);
  raw[0] = group11_clip(raw[0], -1.0f, 1.0f);
  u = raw[0] * GROUP11_U_MAX;
  action[0] = u;
  action[1] = u;
}

/* Compatibility alias for firmware that expects an SB3-style name. */
static void sb3_predict(const float state[8], float action[2]) {
  group11_policy_predict(state, action);
}

#endif /* GROUP11_POLICY_H */
