"""Export trained Group11 policies to a small C header for STM32 firmware.

The exported file contains only deterministic actor inference. Training-only
objects such as value networks, optimizers, replay buffers, and exploration
noise are intentionally omitted.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch.nn as nn
from stable_baselines3 import PPO

from group11_balance.algorithms.naf.model import NAFPolicy
from group11_balance.sim.env import TwoStageBalanceEnv


SUPPORTED_ACTIVATIONS = {
    nn.ReLU: "relu",
    nn.Tanh: "tanh",
    nn.Identity: "identity",
}


@dataclass
class DenseLayer:
    weight: np.ndarray
    bias: np.ndarray
    activation: str = "identity"


def activation_name(module: nn.Module) -> str:
    for cls, name in SUPPORTED_ACTIVATIONS.items():
        if isinstance(module, cls):
            return name
    raise TypeError(f"unsupported activation: {module.__class__.__name__}")


def extract_sequential(seq: nn.Sequential) -> list[DenseLayer]:
    layers: list[DenseLayer] = []
    pending: DenseLayer | None = None
    for module in seq:
        if isinstance(module, nn.Linear):
            if pending is not None:
                layers.append(pending)
            pending = DenseLayer(
                weight=module.weight.detach().cpu().numpy().astype(np.float32),
                bias=module.bias.detach().cpu().numpy().astype(np.float32),
            )
        elif isinstance(module, tuple(SUPPORTED_ACTIVATIONS)):
            if pending is None:
                if isinstance(module, nn.Identity):
                    continue
                raise TypeError(f"activation without preceding linear layer: {module}")
            pending.activation = activation_name(module)
        elif isinstance(module, nn.Flatten):
            continue
        else:
            raise TypeError(f"unsupported module: {module.__class__.__name__}")
    if pending is not None:
        layers.append(pending)
    return layers


def append_linear(layers: list[DenseLayer], module: nn.Linear, activation: str = "identity") -> None:
    layers.append(
        DenseLayer(
            weight=module.weight.detach().cpu().numpy().astype(np.float32),
            bias=module.bias.detach().cpu().numpy().astype(np.float32),
            activation=activation,
        )
    )


def extract_ppo_layers(path: str, device: str) -> list[DenseLayer]:
    model = PPO.load(path, device=device)
    layers = extract_sequential(model.policy.mlp_extractor.policy_net)
    append_linear(layers, model.policy.action_net)
    return layers


def extract_naf_layers(path: str, device: str) -> list[DenseLayer]:
    policy = NAFPolicy.load(path, device=device)
    return extract_sequential(policy.network.mu_net)


def validate_layers(layers: list[DenseLayer]) -> None:
    if not layers:
        raise ValueError("no linear layers found in actor")
    if layers[0].weight.shape[1] != 8:
        raise ValueError(f"expected 8-D state input, got {layers[0].weight.shape[1]}")
    if layers[-1].weight.shape[0] != 1:
        raise ValueError(f"expected 1-D normalized common action, got {layers[-1].weight.shape[0]}")


def forward_layers(obs: np.ndarray, layers: list[DenseLayer]) -> np.ndarray:
    x = np.asarray(obs, dtype=np.float32)
    for layer in layers:
        x = layer.weight @ x + layer.bias
        if layer.activation == "relu":
            x = np.maximum(x, 0.0)
        elif layer.activation == "tanh":
            x = np.tanh(x)
        elif layer.activation == "identity":
            pass
        else:
            raise ValueError(f"unknown activation: {layer.activation}")
    return np.clip(x, -1.0, 1.0).astype(np.float32)


def c_float(value: float) -> str:
    return f"{float(value):.8e}f"


def c_matrix(name: str, value: np.ndarray) -> list[str]:
    rows, cols = value.shape
    lines = [f"static const float {name}[{rows}][{cols}] = {{"]
    for row in value:
        lines.append("  {" + ", ".join(c_float(x) for x in row) + "},")
    lines.append("};")
    return lines


def c_vector(name: str, value: np.ndarray) -> list[str]:
    return [f"static const float {name}[{len(value)}] = {{" + ", ".join(c_float(x) for x in value) + "};"]


def generate_header(*, layers: list[DenseLayer], algo: str, u_max: float) -> str:
    max_width = max(max(layer.weight.shape) for layer in layers)
    param_count = sum(layer.weight.size + layer.bias.size for layer in layers)
    lines = [
        "/* Auto-generated by group11_balance.deploy.export_to_c.py -- DO NOT EDIT */",
        "#ifndef GROUP11_POLICY_H",
        "#define GROUP11_POLICY_H",
        "",
        "#include <math.h>",
        "",
        f"#define GROUP11_ALGO_{algo.upper()} 1",
        f"#define GROUP11_NUM_LAYERS {len(layers)}",
        "#define GROUP11_OBS_DIM 8",
        "#define GROUP11_ACTION_DIM 1",
        f"#define GROUP11_MAX_WIDTH {max_width}",
        f"#define GROUP11_PARAM_COUNT {param_count}",
        f"#define GROUP11_U_MAX {c_float(u_max)}",
        "",
        "/*",
        "state order:",
        "  theta_l, theta_r, theta_l_dot, theta_r_dot,",
        "  body_angle, body_rate, pole_angle, pole_rate",
        "action output:",
        "  action[0], action[1] are physical left/right wheel control values.",
        "  The learned actor emits one normalized common-mode action in [-1, 1],",
        "  then this header maps it to [u, u] by multiplying GROUP11_U_MAX.",
        "*/",
        "",
    ]

    for idx, layer in enumerate(layers):
        lines.extend(c_matrix(f"GROUP11_W{idx}", layer.weight))
        lines.extend(c_vector(f"GROUP11_B{idx}", layer.bias))
        lines.append(f"#define GROUP11_LAYER{idx}_IN {layer.weight.shape[1]}")
        lines.append(f"#define GROUP11_LAYER{idx}_OUT {layer.weight.shape[0]}")
        lines.append(f"#define GROUP11_LAYER{idx}_ACT_{layer.activation.upper()} 1")
        lines.append("")

    lines.extend(
        [
            "static float group11_clip(float x, float lo, float hi) {",
            "  if (x < lo) return lo;",
            "  if (x > hi) return hi;",
            "  return x;",
            "}",
            "",
            "static float group11_activation(float x, int act_id) {",
            "  if (act_id == 1) return x > 0.0f ? x : 0.0f;",
            "  if (act_id == 2) return tanhf(x);",
            "  return x;",
            "}",
            "",
            "static void group11_dense(const float *in, float *out, const float *w, const float *b, int in_dim, int out_dim, int act_id) {",
            "  int i, j;",
            "  for (i = 0; i < out_dim; i++) {",
            "    float y = b[i];",
            "    for (j = 0; j < in_dim; j++) y += w[i * in_dim + j] * in[j];",
            "    out[i] = group11_activation(y, act_id);",
            "  }",
            "}",
            "",
            "static void group11_policy_raw(const float state[8], float raw[1]) {",
            "  float buf0[GROUP11_MAX_WIDTH];",
            "  float buf1[GROUP11_MAX_WIDTH];",
            "  const float *in = state;",
            "",
        ]
    )

    for idx, layer in enumerate(layers):
        act_id = {"identity": 0, "relu": 1, "tanh": 2}[layer.activation]
        out_name = "raw" if idx == len(layers) - 1 else ("buf0" if idx % 2 == 0 else "buf1")
        lines.append(
            f"  group11_dense(in, {out_name}, (const float *)GROUP11_W{idx}, GROUP11_B{idx}, "
            f"GROUP11_LAYER{idx}_IN, GROUP11_LAYER{idx}_OUT, {act_id});"
        )
        if idx != len(layers) - 1:
            lines.append(f"  in = {out_name};")
        lines.append("")

    lines.extend(
        [
            "}",
            "",
            "static void group11_policy_predict(const float state[8], float action[2]) {",
            "  float raw[1];",
            "  float u;",
            "  group11_policy_raw(state, raw);",
            "  raw[0] = group11_clip(raw[0], -1.0f, 1.0f);",
            "  u = raw[0] * GROUP11_U_MAX;",
            "  action[0] = u;",
            "  action[1] = u;",
            "}",
            "",
            "/* Compatibility alias for firmware that expects an SB3-style name. */",
            "static void sb3_predict(const float state[8], float action[2]) {",
            "  group11_policy_predict(state, action);",
            "}",
            "",
            "#endif /* GROUP11_POLICY_H */",
            "",
        ]
    )
    return "\n".join(lines)


def check_export(path: str, algo: str, layers: list[DenseLayer], u_max: float, device: str, seed: int) -> float:
    env = TwoStageBalanceEnv()
    rng = np.random.default_rng(seed)
    if algo == "PPO":
        model = PPO.load(path, device=device)
    elif algo == "NAF":
        model = NAFPolicy.load(path, device=device)
    else:
        raise ValueError(f"unknown algo: {algo}")

    max_err = 0.0
    for _ in range(64):
        obs = rng.uniform(env.observation_space.low, env.observation_space.high).astype(np.float32)
        model_action, _ = model.predict(obs, deterministic=True)
        model_u = float(np.clip(np.asarray(model_action).reshape(-1)[0], -1.0, 1.0) * u_max)
        exported = forward_layers(obs, layers)
        exported_u = float(exported[0] * u_max)
        max_err = max(max_err, abs(model_u - exported_u))
    return max_err


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--algo", choices=["PPO", "NAF"], required=True)
    parser.add_argument("--model", required=True)
    parser.add_argument("--output", default="outputs/firmware/group11_policy.h")
    parser.add_argument("--u-max", type=float, default=200.0)
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--no-check", action="store_true")
    args = parser.parse_args()

    if args.algo == "PPO":
        layers = extract_ppo_layers(args.model, args.device)
    else:
        layers = extract_naf_layers(args.model, args.device)
    validate_layers(layers)

    header = generate_header(layers=layers, algo=args.algo, u_max=args.u_max)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(header, encoding="utf-8")

    param_count = sum(layer.weight.size + layer.bias.size for layer in layers)
    print(f"Exported {args.algo} deterministic actor to {output}")
    print(f"  layers: {[tuple(layer.weight.shape) for layer in layers]}")
    print(f"  activations: {[layer.activation for layer in layers]}, final=clip")
    print(f"  action: normalized common-mode [-1,1] -> physical [u,u], u_max={args.u_max}")
    print(f"  params: {param_count} float32 = {param_count * 4} bytes")
    print("  function: group11_policy_predict(state, action)")

    if not args.no_check:
        max_err = check_export(args.model, args.algo, layers, args.u_max, args.device, seed=0)
        print(f"  Python/export max_abs_physical_error: {max_err:.3e}")
        if max_err > 1e-3:
            raise SystemExit("exported policy does not match Python deterministic actor")


if __name__ == "__main__":
    main()
